package com.aldt.test.dao.mapper.loanCollection;

import com.aldt.test.dao.domain.loanCollection.CollectionCase;

public interface CollectionCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    int insert(CollectionCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    int insertSelective(CollectionCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    CollectionCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CollectionCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CollectionCase record);


    CollectionCase selectLastCaseByUserId(Integer userId);

}