package com.aldt.test.dao.domain.loanCollection;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CollectionCase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.app
     *
     * @mbg.generated
     */
    private Integer app;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.userId
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.queue
     *
     * @mbg.generated
     */
    private Byte queue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.queueTag
     *
     * @mbg.generated
     */
    private Byte queueTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.collectionStatus
     *
     * @mbg.generated
     */
    private Byte collectionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.operateStatus
     *
     * @mbg.generated
     */
    private Byte operateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.closeReason
     *
     * @mbg.generated
     */
    private Byte closeReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.closeTime
     *
     * @mbg.generated
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.sysUserId
     *
     * @mbg.generated
     */
    private Long sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.allocateTime
     *
     * @mbg.generated
     */
    private Date allocateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.orderNum
     *
     * @mbg.generated
     */
    private Byte orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.singlePremiumStatus
     *
     * @mbg.generated
     */
    private Byte singlePremiumStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.singleAmount
     *
     * @mbg.generated
     */
    private BigDecimal singleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.singleRemainAmount
     *
     * @mbg.generated
     */
    private BigDecimal singleRemainAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.singleOverdueDays
     *
     * @mbg.generated
     */
    private Short singleOverdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.singleOverdueAmount
     *
     * @mbg.generated
     */
    private BigDecimal singleOverdueAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.overdueDays
     *
     * @mbg.generated
     */
    private Short overdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.overdueAmount
     *
     * @mbg.generated
     */
    private BigDecimal overdueAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.loanAmount
     *
     * @mbg.generated
     */
    private BigDecimal loanAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.caseAmount
     *
     * @mbg.generated
     */
    private BigDecimal caseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.remainAmount
     *
     * @mbg.generated
     */
    private BigDecimal remainAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.remainCapitalAmount
     *
     * @mbg.generated
     */
    private BigDecimal remainCapitalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.banks
     *
     * @mbg.generated
     */
    private String banks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.lastFollowDate
     *
     * @mbg.generated
     */
    private Date lastFollowDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.nextFollowDate
     *
     * @mbg.generated
     */
    private Date nextFollowDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.billAge
     *
     * @mbg.generated
     */
    private String billAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.billAgePart
     *
     * @mbg.generated
     */
    private String billAgePart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.delegateOrgId
     *
     * @mbg.generated
     */
    private Integer delegateOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.delegateNum
     *
     * @mbg.generated
     */
    private Byte delegateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coll_collection_case.lastUpdateTime
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.id
     *
     * @return the value of coll_collection_case.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.id
     *
     * @param id the value for coll_collection_case.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.app
     *
     * @return the value of coll_collection_case.app
     *
     * @mbg.generated
     */
    public Integer getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.app
     *
     * @param app the value for coll_collection_case.app
     *
     * @mbg.generated
     */
    public void setApp(Integer app) {
        this.app = app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.userId
     *
     * @return the value of coll_collection_case.userId
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.userId
     *
     * @param userId the value for coll_collection_case.userId
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.userName
     *
     * @return the value of coll_collection_case.userName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.userName
     *
     * @param userName the value for coll_collection_case.userName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.queue
     *
     * @return the value of coll_collection_case.queue
     *
     * @mbg.generated
     */
    public Byte getQueue() {
        return queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.queue
     *
     * @param queue the value for coll_collection_case.queue
     *
     * @mbg.generated
     */
    public void setQueue(Byte queue) {
        this.queue = queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.queueTag
     *
     * @return the value of coll_collection_case.queueTag
     *
     * @mbg.generated
     */
    public Byte getQueueTag() {
        return queueTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.queueTag
     *
     * @param queueTag the value for coll_collection_case.queueTag
     *
     * @mbg.generated
     */
    public void setQueueTag(Byte queueTag) {
        this.queueTag = queueTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.collectionStatus
     *
     * @return the value of coll_collection_case.collectionStatus
     *
     * @mbg.generated
     */
    public Byte getCollectionStatus() {
        return collectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.collectionStatus
     *
     * @param collectionStatus the value for coll_collection_case.collectionStatus
     *
     * @mbg.generated
     */
    public void setCollectionStatus(Byte collectionStatus) {
        this.collectionStatus = collectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.status
     *
     * @return the value of coll_collection_case.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.status
     *
     * @param status the value for coll_collection_case.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.operateStatus
     *
     * @return the value of coll_collection_case.operateStatus
     *
     * @mbg.generated
     */
    public Byte getOperateStatus() {
        return operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.operateStatus
     *
     * @param operateStatus the value for coll_collection_case.operateStatus
     *
     * @mbg.generated
     */
    public void setOperateStatus(Byte operateStatus) {
        this.operateStatus = operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.closeReason
     *
     * @return the value of coll_collection_case.closeReason
     *
     * @mbg.generated
     */
    public Byte getCloseReason() {
        return closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.closeReason
     *
     * @param closeReason the value for coll_collection_case.closeReason
     *
     * @mbg.generated
     */
    public void setCloseReason(Byte closeReason) {
        this.closeReason = closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.closeTime
     *
     * @return the value of coll_collection_case.closeTime
     *
     * @mbg.generated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.closeTime
     *
     * @param closeTime the value for coll_collection_case.closeTime
     *
     * @mbg.generated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.sysUserId
     *
     * @return the value of coll_collection_case.sysUserId
     *
     * @mbg.generated
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.sysUserId
     *
     * @param sysUserId the value for coll_collection_case.sysUserId
     *
     * @mbg.generated
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.allocateTime
     *
     * @return the value of coll_collection_case.allocateTime
     *
     * @mbg.generated
     */
    public Date getAllocateTime() {
        return allocateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.allocateTime
     *
     * @param allocateTime the value for coll_collection_case.allocateTime
     *
     * @mbg.generated
     */
    public void setAllocateTime(Date allocateTime) {
        this.allocateTime = allocateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.orderNum
     *
     * @return the value of coll_collection_case.orderNum
     *
     * @mbg.generated
     */
    public Byte getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.orderNum
     *
     * @param orderNum the value for coll_collection_case.orderNum
     *
     * @mbg.generated
     */
    public void setOrderNum(Byte orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.singlePremiumStatus
     *
     * @return the value of coll_collection_case.singlePremiumStatus
     *
     * @mbg.generated
     */
    public Byte getSinglePremiumStatus() {
        return singlePremiumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.singlePremiumStatus
     *
     * @param singlePremiumStatus the value for coll_collection_case.singlePremiumStatus
     *
     * @mbg.generated
     */
    public void setSinglePremiumStatus(Byte singlePremiumStatus) {
        this.singlePremiumStatus = singlePremiumStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.singleAmount
     *
     * @return the value of coll_collection_case.singleAmount
     *
     * @mbg.generated
     */
    public BigDecimal getSingleAmount() {
        return singleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.singleAmount
     *
     * @param singleAmount the value for coll_collection_case.singleAmount
     *
     * @mbg.generated
     */
    public void setSingleAmount(BigDecimal singleAmount) {
        this.singleAmount = singleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.singleRemainAmount
     *
     * @return the value of coll_collection_case.singleRemainAmount
     *
     * @mbg.generated
     */
    public BigDecimal getSingleRemainAmount() {
        return singleRemainAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.singleRemainAmount
     *
     * @param singleRemainAmount the value for coll_collection_case.singleRemainAmount
     *
     * @mbg.generated
     */
    public void setSingleRemainAmount(BigDecimal singleRemainAmount) {
        this.singleRemainAmount = singleRemainAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.singleOverdueDays
     *
     * @return the value of coll_collection_case.singleOverdueDays
     *
     * @mbg.generated
     */
    public Short getSingleOverdueDays() {
        return singleOverdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.singleOverdueDays
     *
     * @param singleOverdueDays the value for coll_collection_case.singleOverdueDays
     *
     * @mbg.generated
     */
    public void setSingleOverdueDays(Short singleOverdueDays) {
        this.singleOverdueDays = singleOverdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.singleOverdueAmount
     *
     * @return the value of coll_collection_case.singleOverdueAmount
     *
     * @mbg.generated
     */
    public BigDecimal getSingleOverdueAmount() {
        return singleOverdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.singleOverdueAmount
     *
     * @param singleOverdueAmount the value for coll_collection_case.singleOverdueAmount
     *
     * @mbg.generated
     */
    public void setSingleOverdueAmount(BigDecimal singleOverdueAmount) {
        this.singleOverdueAmount = singleOverdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.overdueDays
     *
     * @return the value of coll_collection_case.overdueDays
     *
     * @mbg.generated
     */
    public Short getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.overdueDays
     *
     * @param overdueDays the value for coll_collection_case.overdueDays
     *
     * @mbg.generated
     */
    public void setOverdueDays(Short overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.overdueAmount
     *
     * @return the value of coll_collection_case.overdueAmount
     *
     * @mbg.generated
     */
    public BigDecimal getOverdueAmount() {
        return overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.overdueAmount
     *
     * @param overdueAmount the value for coll_collection_case.overdueAmount
     *
     * @mbg.generated
     */
    public void setOverdueAmount(BigDecimal overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.loanAmount
     *
     * @return the value of coll_collection_case.loanAmount
     *
     * @mbg.generated
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.loanAmount
     *
     * @param loanAmount the value for coll_collection_case.loanAmount
     *
     * @mbg.generated
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.caseAmount
     *
     * @return the value of coll_collection_case.caseAmount
     *
     * @mbg.generated
     */
    public BigDecimal getCaseAmount() {
        return caseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.caseAmount
     *
     * @param caseAmount the value for coll_collection_case.caseAmount
     *
     * @mbg.generated
     */
    public void setCaseAmount(BigDecimal caseAmount) {
        this.caseAmount = caseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.remainAmount
     *
     * @return the value of coll_collection_case.remainAmount
     *
     * @mbg.generated
     */
    public BigDecimal getRemainAmount() {
        return remainAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.remainAmount
     *
     * @param remainAmount the value for coll_collection_case.remainAmount
     *
     * @mbg.generated
     */
    public void setRemainAmount(BigDecimal remainAmount) {
        this.remainAmount = remainAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.remainCapitalAmount
     *
     * @return the value of coll_collection_case.remainCapitalAmount
     *
     * @mbg.generated
     */
    public BigDecimal getRemainCapitalAmount() {
        return remainCapitalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.remainCapitalAmount
     *
     * @param remainCapitalAmount the value for coll_collection_case.remainCapitalAmount
     *
     * @mbg.generated
     */
    public void setRemainCapitalAmount(BigDecimal remainCapitalAmount) {
        this.remainCapitalAmount = remainCapitalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.banks
     *
     * @return the value of coll_collection_case.banks
     *
     * @mbg.generated
     */
    public String getBanks() {
        return banks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.banks
     *
     * @param banks the value for coll_collection_case.banks
     *
     * @mbg.generated
     */
    public void setBanks(String banks) {
        this.banks = banks == null ? null : banks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.lastFollowDate
     *
     * @return the value of coll_collection_case.lastFollowDate
     *
     * @mbg.generated
     */
    public Date getLastFollowDate() {
        return lastFollowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.lastFollowDate
     *
     * @param lastFollowDate the value for coll_collection_case.lastFollowDate
     *
     * @mbg.generated
     */
    public void setLastFollowDate(Date lastFollowDate) {
        this.lastFollowDate = lastFollowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.nextFollowDate
     *
     * @return the value of coll_collection_case.nextFollowDate
     *
     * @mbg.generated
     */
    public Date getNextFollowDate() {
        return nextFollowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.nextFollowDate
     *
     * @param nextFollowDate the value for coll_collection_case.nextFollowDate
     *
     * @mbg.generated
     */
    public void setNextFollowDate(Date nextFollowDate) {
        this.nextFollowDate = nextFollowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.billAge
     *
     * @return the value of coll_collection_case.billAge
     *
     * @mbg.generated
     */
    public String getBillAge() {
        return billAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.billAge
     *
     * @param billAge the value for coll_collection_case.billAge
     *
     * @mbg.generated
     */
    public void setBillAge(String billAge) {
        this.billAge = billAge == null ? null : billAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.billAgePart
     *
     * @return the value of coll_collection_case.billAgePart
     *
     * @mbg.generated
     */
    public String getBillAgePart() {
        return billAgePart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.billAgePart
     *
     * @param billAgePart the value for coll_collection_case.billAgePart
     *
     * @mbg.generated
     */
    public void setBillAgePart(String billAgePart) {
        this.billAgePart = billAgePart == null ? null : billAgePart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.delegateOrgId
     *
     * @return the value of coll_collection_case.delegateOrgId
     *
     * @mbg.generated
     */
    public Integer getDelegateOrgId() {
        return delegateOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.delegateOrgId
     *
     * @param delegateOrgId the value for coll_collection_case.delegateOrgId
     *
     * @mbg.generated
     */
    public void setDelegateOrgId(Integer delegateOrgId) {
        this.delegateOrgId = delegateOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.delegateNum
     *
     * @return the value of coll_collection_case.delegateNum
     *
     * @mbg.generated
     */
    public Byte getDelegateNum() {
        return delegateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.delegateNum
     *
     * @param delegateNum the value for coll_collection_case.delegateNum
     *
     * @mbg.generated
     */
    public void setDelegateNum(Byte delegateNum) {
        this.delegateNum = delegateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.memo
     *
     * @return the value of coll_collection_case.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.memo
     *
     * @param memo the value for coll_collection_case.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.createTime
     *
     * @return the value of coll_collection_case.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.createTime
     *
     * @param createTime the value for coll_collection_case.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coll_collection_case.lastUpdateTime
     *
     * @return the value of coll_collection_case.lastUpdateTime
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coll_collection_case.lastUpdateTime
     *
     * @param lastUpdateTime the value for coll_collection_case.lastUpdateTime
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coll_collection_case
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", app=").append(app);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", queue=").append(queue);
        sb.append(", queueTag=").append(queueTag);
        sb.append(", collectionStatus=").append(collectionStatus);
        sb.append(", status=").append(status);
        sb.append(", operateStatus=").append(operateStatus);
        sb.append(", closeReason=").append(closeReason);
        sb.append(", closeTime=").append(closeTime);
        sb.append(", sysUserId=").append(sysUserId);
        sb.append(", allocateTime=").append(allocateTime);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", singlePremiumStatus=").append(singlePremiumStatus);
        sb.append(", singleAmount=").append(singleAmount);
        sb.append(", singleRemainAmount=").append(singleRemainAmount);
        sb.append(", singleOverdueDays=").append(singleOverdueDays);
        sb.append(", singleOverdueAmount=").append(singleOverdueAmount);
        sb.append(", overdueDays=").append(overdueDays);
        sb.append(", overdueAmount=").append(overdueAmount);
        sb.append(", loanAmount=").append(loanAmount);
        sb.append(", caseAmount=").append(caseAmount);
        sb.append(", remainAmount=").append(remainAmount);
        sb.append(", remainCapitalAmount=").append(remainCapitalAmount);
        sb.append(", banks=").append(banks);
        sb.append(", lastFollowDate=").append(lastFollowDate);
        sb.append(", nextFollowDate=").append(nextFollowDate);
        sb.append(", billAge=").append(billAge);
        sb.append(", billAgePart=").append(billAgePart);
        sb.append(", delegateOrgId=").append(delegateOrgId);
        sb.append(", delegateNum=").append(delegateNum);
        sb.append(", memo=").append(memo);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}