package com.aldt.test.dao.mapper.loandb;

import com.aldt.test.dao.domain.loandb.UserCreditRisk;
import com.aldt.test.dao.domain.loandb.UserCreditRiskCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UserCreditRiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int countByExample(UserCreditRiskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int deleteByExample(UserCreditRiskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int insert(UserCreditRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int insertSelective(UserCreditRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    List<UserCreditRisk> selectByExampleWithRowbounds(UserCreditRiskCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    List<UserCreditRisk> selectByExample(UserCreditRiskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    UserCreditRisk selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserCreditRisk record, @Param("example") UserCreditRiskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int updateByExample(@Param("record") UserCreditRisk record, @Param("example") UserCreditRiskCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int updateByPrimaryKeySelective(UserCreditRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    int updateByPrimaryKey(UserCreditRisk record);
}