package com.aldt.test.dao.domain.loandb;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserCreditRisk implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.Id
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.UserId
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.ScorecardModel
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte scorecardModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.RiskRank
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String riskRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.ActivityScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer activityScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.CreditModel
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String creditModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.Coefficient
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private BigDecimal coefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.SocialFundCoefficientForCredit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private BigDecimal socialFundCoefficientForCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.UpperLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private BigDecimal upperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.CreditResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Boolean creditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.AuditFlowFlag
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Boolean auditFlowFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.FinalResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String finalResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.FinalRoute
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String finalRoute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.CreditLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private BigDecimal creditLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.FinalLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private BigDecimal finalLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.ArtificialRoute
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte artificialRoute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.FobScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer fobScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.FobRank
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte fobRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.CashOutScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer cashOutScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.AapplyScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer aapplyScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.CreateDate
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.LastUpdateDate
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.MannualAuditResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte mannualAuditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.HitGrayCnt
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer hitGrayCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.IsRefused
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Boolean isRefused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.StepCode
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte stepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.Step
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.BSCreditComment
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String BSCreditComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.BatchTime
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Date batchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.user_loaning_type
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte user_loaning_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.adjust_type
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Byte adjust_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.credit_date
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Date credit_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.RiskPricingRankBasis
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String riskPricingRankBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.OrderId
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.ProductCode
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit_risk.NodeInfo
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private String nodeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.Id
     *
     * @return the value of t_user_credit_risk.Id
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.Id
     *
     * @param id the value for t_user_credit_risk.Id
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.UserId
     *
     * @return the value of t_user_credit_risk.UserId
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.UserId
     *
     * @param userId the value for t_user_credit_risk.UserId
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.ScorecardModel
     *
     * @return the value of t_user_credit_risk.ScorecardModel
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getScorecardModel() {
        return scorecardModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.ScorecardModel
     *
     * @param scorecardModel the value for t_user_credit_risk.ScorecardModel
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setScorecardModel(Byte scorecardModel) {
        this.scorecardModel = scorecardModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.RiskRank
     *
     * @return the value of t_user_credit_risk.RiskRank
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getRiskRank() {
        return riskRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.RiskRank
     *
     * @param riskRank the value for t_user_credit_risk.RiskRank
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setRiskRank(String riskRank) {
        this.riskRank = riskRank == null ? null : riskRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.ActivityScore
     *
     * @return the value of t_user_credit_risk.ActivityScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getActivityScore() {
        return activityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.ActivityScore
     *
     * @param activityScore the value for t_user_credit_risk.ActivityScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setActivityScore(Integer activityScore) {
        this.activityScore = activityScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.CreditModel
     *
     * @return the value of t_user_credit_risk.CreditModel
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getCreditModel() {
        return creditModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.CreditModel
     *
     * @param creditModel the value for t_user_credit_risk.CreditModel
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCreditModel(String creditModel) {
        this.creditModel = creditModel == null ? null : creditModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.Coefficient
     *
     * @return the value of t_user_credit_risk.Coefficient
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public BigDecimal getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.Coefficient
     *
     * @param coefficient the value for t_user_credit_risk.Coefficient
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCoefficient(BigDecimal coefficient) {
        this.coefficient = coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.SocialFundCoefficientForCredit
     *
     * @return the value of t_user_credit_risk.SocialFundCoefficientForCredit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public BigDecimal getSocialFundCoefficientForCredit() {
        return socialFundCoefficientForCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.SocialFundCoefficientForCredit
     *
     * @param socialFundCoefficientForCredit the value for t_user_credit_risk.SocialFundCoefficientForCredit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setSocialFundCoefficientForCredit(BigDecimal socialFundCoefficientForCredit) {
        this.socialFundCoefficientForCredit = socialFundCoefficientForCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.UpperLimit
     *
     * @return the value of t_user_credit_risk.UpperLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public BigDecimal getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.UpperLimit
     *
     * @param upperLimit the value for t_user_credit_risk.UpperLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setUpperLimit(BigDecimal upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.CreditResult
     *
     * @return the value of t_user_credit_risk.CreditResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Boolean getCreditResult() {
        return creditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.CreditResult
     *
     * @param creditResult the value for t_user_credit_risk.CreditResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCreditResult(Boolean creditResult) {
        this.creditResult = creditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.AuditFlowFlag
     *
     * @return the value of t_user_credit_risk.AuditFlowFlag
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Boolean getAuditFlowFlag() {
        return auditFlowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.AuditFlowFlag
     *
     * @param auditFlowFlag the value for t_user_credit_risk.AuditFlowFlag
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setAuditFlowFlag(Boolean auditFlowFlag) {
        this.auditFlowFlag = auditFlowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.FinalResult
     *
     * @return the value of t_user_credit_risk.FinalResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getFinalResult() {
        return finalResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.FinalResult
     *
     * @param finalResult the value for t_user_credit_risk.FinalResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setFinalResult(String finalResult) {
        this.finalResult = finalResult == null ? null : finalResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.FinalRoute
     *
     * @return the value of t_user_credit_risk.FinalRoute
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getFinalRoute() {
        return finalRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.FinalRoute
     *
     * @param finalRoute the value for t_user_credit_risk.FinalRoute
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setFinalRoute(String finalRoute) {
        this.finalRoute = finalRoute == null ? null : finalRoute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.CreditLimit
     *
     * @return the value of t_user_credit_risk.CreditLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.CreditLimit
     *
     * @param creditLimit the value for t_user_credit_risk.CreditLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.FinalLimit
     *
     * @return the value of t_user_credit_risk.FinalLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public BigDecimal getFinalLimit() {
        return finalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.FinalLimit
     *
     * @param finalLimit the value for t_user_credit_risk.FinalLimit
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setFinalLimit(BigDecimal finalLimit) {
        this.finalLimit = finalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.ArtificialRoute
     *
     * @return the value of t_user_credit_risk.ArtificialRoute
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getArtificialRoute() {
        return artificialRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.ArtificialRoute
     *
     * @param artificialRoute the value for t_user_credit_risk.ArtificialRoute
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setArtificialRoute(Byte artificialRoute) {
        this.artificialRoute = artificialRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.FobScore
     *
     * @return the value of t_user_credit_risk.FobScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getFobScore() {
        return fobScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.FobScore
     *
     * @param fobScore the value for t_user_credit_risk.FobScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setFobScore(Integer fobScore) {
        this.fobScore = fobScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.FobRank
     *
     * @return the value of t_user_credit_risk.FobRank
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getFobRank() {
        return fobRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.FobRank
     *
     * @param fobRank the value for t_user_credit_risk.FobRank
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setFobRank(Byte fobRank) {
        this.fobRank = fobRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.CashOutScore
     *
     * @return the value of t_user_credit_risk.CashOutScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getCashOutScore() {
        return cashOutScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.CashOutScore
     *
     * @param cashOutScore the value for t_user_credit_risk.CashOutScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCashOutScore(Integer cashOutScore) {
        this.cashOutScore = cashOutScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.AapplyScore
     *
     * @return the value of t_user_credit_risk.AapplyScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getAapplyScore() {
        return aapplyScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.AapplyScore
     *
     * @param aapplyScore the value for t_user_credit_risk.AapplyScore
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setAapplyScore(Integer aapplyScore) {
        this.aapplyScore = aapplyScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.CreateDate
     *
     * @return the value of t_user_credit_risk.CreateDate
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.CreateDate
     *
     * @param createDate the value for t_user_credit_risk.CreateDate
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.LastUpdateDate
     *
     * @return the value of t_user_credit_risk.LastUpdateDate
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.LastUpdateDate
     *
     * @param lastUpdateDate the value for t_user_credit_risk.LastUpdateDate
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.MannualAuditResult
     *
     * @return the value of t_user_credit_risk.MannualAuditResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getMannualAuditResult() {
        return mannualAuditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.MannualAuditResult
     *
     * @param mannualAuditResult the value for t_user_credit_risk.MannualAuditResult
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setMannualAuditResult(Byte mannualAuditResult) {
        this.mannualAuditResult = mannualAuditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.HitGrayCnt
     *
     * @return the value of t_user_credit_risk.HitGrayCnt
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getHitGrayCnt() {
        return hitGrayCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.HitGrayCnt
     *
     * @param hitGrayCnt the value for t_user_credit_risk.HitGrayCnt
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setHitGrayCnt(Integer hitGrayCnt) {
        this.hitGrayCnt = hitGrayCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.IsRefused
     *
     * @return the value of t_user_credit_risk.IsRefused
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Boolean getIsRefused() {
        return isRefused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.IsRefused
     *
     * @param isRefused the value for t_user_credit_risk.IsRefused
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setIsRefused(Boolean isRefused) {
        this.isRefused = isRefused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.StepCode
     *
     * @return the value of t_user_credit_risk.StepCode
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getStepCode() {
        return stepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.StepCode
     *
     * @param stepCode the value for t_user_credit_risk.StepCode
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setStepCode(Byte stepCode) {
        this.stepCode = stepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.Step
     *
     * @return the value of t_user_credit_risk.Step
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.Step
     *
     * @param step the value for t_user_credit_risk.Step
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.BSCreditComment
     *
     * @return the value of t_user_credit_risk.BSCreditComment
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getBSCreditComment() {
        return BSCreditComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.BSCreditComment
     *
     * @param BSCreditComment the value for t_user_credit_risk.BSCreditComment
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setBSCreditComment(String BSCreditComment) {
        this.BSCreditComment = BSCreditComment == null ? null : BSCreditComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.BatchTime
     *
     * @return the value of t_user_credit_risk.BatchTime
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Date getBatchTime() {
        return batchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.BatchTime
     *
     * @param batchTime the value for t_user_credit_risk.BatchTime
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setBatchTime(Date batchTime) {
        this.batchTime = batchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.user_loaning_type
     *
     * @return the value of t_user_credit_risk.user_loaning_type
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getUser_loaning_type() {
        return user_loaning_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.user_loaning_type
     *
     * @param user_loaning_type the value for t_user_credit_risk.user_loaning_type
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setUser_loaning_type(Byte user_loaning_type) {
        this.user_loaning_type = user_loaning_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.adjust_type
     *
     * @return the value of t_user_credit_risk.adjust_type
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Byte getAdjust_type() {
        return adjust_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.adjust_type
     *
     * @param adjust_type the value for t_user_credit_risk.adjust_type
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setAdjust_type(Byte adjust_type) {
        this.adjust_type = adjust_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.credit_date
     *
     * @return the value of t_user_credit_risk.credit_date
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Date getCredit_date() {
        return credit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.credit_date
     *
     * @param credit_date the value for t_user_credit_risk.credit_date
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setCredit_date(Date credit_date) {
        this.credit_date = credit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.RiskPricingRankBasis
     *
     * @return the value of t_user_credit_risk.RiskPricingRankBasis
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getRiskPricingRankBasis() {
        return riskPricingRankBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.RiskPricingRankBasis
     *
     * @param riskPricingRankBasis the value for t_user_credit_risk.RiskPricingRankBasis
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setRiskPricingRankBasis(String riskPricingRankBasis) {
        this.riskPricingRankBasis = riskPricingRankBasis == null ? null : riskPricingRankBasis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.OrderId
     *
     * @return the value of t_user_credit_risk.OrderId
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.OrderId
     *
     * @param orderId the value for t_user_credit_risk.OrderId
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.ProductCode
     *
     * @return the value of t_user_credit_risk.ProductCode
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.ProductCode
     *
     * @param productCode the value for t_user_credit_risk.ProductCode
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit_risk.NodeInfo
     *
     * @return the value of t_user_credit_risk.NodeInfo
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getNodeInfo() {
        return nodeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit_risk.NodeInfo
     *
     * @param nodeInfo the value for t_user_credit_risk.NodeInfo
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setNodeInfo(String nodeInfo) {
        this.nodeInfo = nodeInfo == null ? null : nodeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", scorecardModel=").append(scorecardModel);
        sb.append(", riskRank=").append(riskRank);
        sb.append(", activityScore=").append(activityScore);
        sb.append(", creditModel=").append(creditModel);
        sb.append(", coefficient=").append(coefficient);
        sb.append(", socialFundCoefficientForCredit=").append(socialFundCoefficientForCredit);
        sb.append(", upperLimit=").append(upperLimit);
        sb.append(", creditResult=").append(creditResult);
        sb.append(", auditFlowFlag=").append(auditFlowFlag);
        sb.append(", finalResult=").append(finalResult);
        sb.append(", finalRoute=").append(finalRoute);
        sb.append(", creditLimit=").append(creditLimit);
        sb.append(", finalLimit=").append(finalLimit);
        sb.append(", artificialRoute=").append(artificialRoute);
        sb.append(", fobScore=").append(fobScore);
        sb.append(", fobRank=").append(fobRank);
        sb.append(", cashOutScore=").append(cashOutScore);
        sb.append(", aapplyScore=").append(aapplyScore);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", mannualAuditResult=").append(mannualAuditResult);
        sb.append(", hitGrayCnt=").append(hitGrayCnt);
        sb.append(", isRefused=").append(isRefused);
        sb.append(", stepCode=").append(stepCode);
        sb.append(", step=").append(step);
        sb.append(", BSCreditComment=").append(BSCreditComment);
        sb.append(", batchTime=").append(batchTime);
        sb.append(", user_loaning_type=").append(user_loaning_type);
        sb.append(", adjust_type=").append(adjust_type);
        sb.append(", credit_date=").append(credit_date);
        sb.append(", riskPricingRankBasis=").append(riskPricingRankBasis);
        sb.append(", orderId=").append(orderId);
        sb.append(", productCode=").append(productCode);
        sb.append(", nodeInfo=").append(nodeInfo);
        sb.append("]");
        return sb.toString();
    }
}