package com.aldt.test.dao.domain.loandb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserCreditRiskCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public UserCreditRiskCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("UserId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("UserId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("UserId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("UserId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("UserId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("UserId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("UserId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("UserId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("UserId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("UserId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("UserId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("UserId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andScorecardModelIsNull() {
            addCriterion("ScorecardModel is null");
            return (Criteria) this;
        }

        public Criteria andScorecardModelIsNotNull() {
            addCriterion("ScorecardModel is not null");
            return (Criteria) this;
        }

        public Criteria andScorecardModelEqualTo(Byte value) {
            addCriterion("ScorecardModel =", value, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelNotEqualTo(Byte value) {
            addCriterion("ScorecardModel <>", value, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelGreaterThan(Byte value) {
            addCriterion("ScorecardModel >", value, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelGreaterThanOrEqualTo(Byte value) {
            addCriterion("ScorecardModel >=", value, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelLessThan(Byte value) {
            addCriterion("ScorecardModel <", value, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelLessThanOrEqualTo(Byte value) {
            addCriterion("ScorecardModel <=", value, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelIn(List<Byte> values) {
            addCriterion("ScorecardModel in", values, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelNotIn(List<Byte> values) {
            addCriterion("ScorecardModel not in", values, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelBetween(Byte value1, Byte value2) {
            addCriterion("ScorecardModel between", value1, value2, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andScorecardModelNotBetween(Byte value1, Byte value2) {
            addCriterion("ScorecardModel not between", value1, value2, "scorecardModel");
            return (Criteria) this;
        }

        public Criteria andRiskRankIsNull() {
            addCriterion("RiskRank is null");
            return (Criteria) this;
        }

        public Criteria andRiskRankIsNotNull() {
            addCriterion("RiskRank is not null");
            return (Criteria) this;
        }

        public Criteria andRiskRankEqualTo(String value) {
            addCriterion("RiskRank =", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankNotEqualTo(String value) {
            addCriterion("RiskRank <>", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankGreaterThan(String value) {
            addCriterion("RiskRank >", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankGreaterThanOrEqualTo(String value) {
            addCriterion("RiskRank >=", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankLessThan(String value) {
            addCriterion("RiskRank <", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankLessThanOrEqualTo(String value) {
            addCriterion("RiskRank <=", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankLike(String value) {
            addCriterion("RiskRank like", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankNotLike(String value) {
            addCriterion("RiskRank not like", value, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankIn(List<String> values) {
            addCriterion("RiskRank in", values, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankNotIn(List<String> values) {
            addCriterion("RiskRank not in", values, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankBetween(String value1, String value2) {
            addCriterion("RiskRank between", value1, value2, "riskRank");
            return (Criteria) this;
        }

        public Criteria andRiskRankNotBetween(String value1, String value2) {
            addCriterion("RiskRank not between", value1, value2, "riskRank");
            return (Criteria) this;
        }

        public Criteria andActivityScoreIsNull() {
            addCriterion("ActivityScore is null");
            return (Criteria) this;
        }

        public Criteria andActivityScoreIsNotNull() {
            addCriterion("ActivityScore is not null");
            return (Criteria) this;
        }

        public Criteria andActivityScoreEqualTo(Integer value) {
            addCriterion("ActivityScore =", value, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreNotEqualTo(Integer value) {
            addCriterion("ActivityScore <>", value, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreGreaterThan(Integer value) {
            addCriterion("ActivityScore >", value, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("ActivityScore >=", value, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreLessThan(Integer value) {
            addCriterion("ActivityScore <", value, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreLessThanOrEqualTo(Integer value) {
            addCriterion("ActivityScore <=", value, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreIn(List<Integer> values) {
            addCriterion("ActivityScore in", values, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreNotIn(List<Integer> values) {
            addCriterion("ActivityScore not in", values, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreBetween(Integer value1, Integer value2) {
            addCriterion("ActivityScore between", value1, value2, "activityScore");
            return (Criteria) this;
        }

        public Criteria andActivityScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("ActivityScore not between", value1, value2, "activityScore");
            return (Criteria) this;
        }

        public Criteria andCreditModelIsNull() {
            addCriterion("CreditModel is null");
            return (Criteria) this;
        }

        public Criteria andCreditModelIsNotNull() {
            addCriterion("CreditModel is not null");
            return (Criteria) this;
        }

        public Criteria andCreditModelEqualTo(String value) {
            addCriterion("CreditModel =", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelNotEqualTo(String value) {
            addCriterion("CreditModel <>", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelGreaterThan(String value) {
            addCriterion("CreditModel >", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelGreaterThanOrEqualTo(String value) {
            addCriterion("CreditModel >=", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelLessThan(String value) {
            addCriterion("CreditModel <", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelLessThanOrEqualTo(String value) {
            addCriterion("CreditModel <=", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelLike(String value) {
            addCriterion("CreditModel like", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelNotLike(String value) {
            addCriterion("CreditModel not like", value, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelIn(List<String> values) {
            addCriterion("CreditModel in", values, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelNotIn(List<String> values) {
            addCriterion("CreditModel not in", values, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelBetween(String value1, String value2) {
            addCriterion("CreditModel between", value1, value2, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCreditModelNotBetween(String value1, String value2) {
            addCriterion("CreditModel not between", value1, value2, "creditModel");
            return (Criteria) this;
        }

        public Criteria andCoefficientIsNull() {
            addCriterion("Coefficient is null");
            return (Criteria) this;
        }

        public Criteria andCoefficientIsNotNull() {
            addCriterion("Coefficient is not null");
            return (Criteria) this;
        }

        public Criteria andCoefficientEqualTo(BigDecimal value) {
            addCriterion("Coefficient =", value, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientNotEqualTo(BigDecimal value) {
            addCriterion("Coefficient <>", value, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientGreaterThan(BigDecimal value) {
            addCriterion("Coefficient >", value, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Coefficient >=", value, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientLessThan(BigDecimal value) {
            addCriterion("Coefficient <", value, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Coefficient <=", value, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientIn(List<BigDecimal> values) {
            addCriterion("Coefficient in", values, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientNotIn(List<BigDecimal> values) {
            addCriterion("Coefficient not in", values, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Coefficient between", value1, value2, "coefficient");
            return (Criteria) this;
        }

        public Criteria andCoefficientNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Coefficient not between", value1, value2, "coefficient");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditIsNull() {
            addCriterion("SocialFundCoefficientForCredit is null");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditIsNotNull() {
            addCriterion("SocialFundCoefficientForCredit is not null");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditEqualTo(BigDecimal value) {
            addCriterion("SocialFundCoefficientForCredit =", value, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditNotEqualTo(BigDecimal value) {
            addCriterion("SocialFundCoefficientForCredit <>", value, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditGreaterThan(BigDecimal value) {
            addCriterion("SocialFundCoefficientForCredit >", value, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SocialFundCoefficientForCredit >=", value, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditLessThan(BigDecimal value) {
            addCriterion("SocialFundCoefficientForCredit <", value, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SocialFundCoefficientForCredit <=", value, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditIn(List<BigDecimal> values) {
            addCriterion("SocialFundCoefficientForCredit in", values, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditNotIn(List<BigDecimal> values) {
            addCriterion("SocialFundCoefficientForCredit not in", values, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SocialFundCoefficientForCredit between", value1, value2, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andSocialFundCoefficientForCreditNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SocialFundCoefficientForCredit not between", value1, value2, "socialFundCoefficientForCredit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitIsNull() {
            addCriterion("UpperLimit is null");
            return (Criteria) this;
        }

        public Criteria andUpperLimitIsNotNull() {
            addCriterion("UpperLimit is not null");
            return (Criteria) this;
        }

        public Criteria andUpperLimitEqualTo(BigDecimal value) {
            addCriterion("UpperLimit =", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitNotEqualTo(BigDecimal value) {
            addCriterion("UpperLimit <>", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitGreaterThan(BigDecimal value) {
            addCriterion("UpperLimit >", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UpperLimit >=", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitLessThan(BigDecimal value) {
            addCriterion("UpperLimit <", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UpperLimit <=", value, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitIn(List<BigDecimal> values) {
            addCriterion("UpperLimit in", values, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitNotIn(List<BigDecimal> values) {
            addCriterion("UpperLimit not in", values, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UpperLimit between", value1, value2, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andUpperLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UpperLimit not between", value1, value2, "upperLimit");
            return (Criteria) this;
        }

        public Criteria andCreditResultIsNull() {
            addCriterion("CreditResult is null");
            return (Criteria) this;
        }

        public Criteria andCreditResultIsNotNull() {
            addCriterion("CreditResult is not null");
            return (Criteria) this;
        }

        public Criteria andCreditResultEqualTo(Boolean value) {
            addCriterion("CreditResult =", value, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultNotEqualTo(Boolean value) {
            addCriterion("CreditResult <>", value, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultGreaterThan(Boolean value) {
            addCriterion("CreditResult >", value, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("CreditResult >=", value, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultLessThan(Boolean value) {
            addCriterion("CreditResult <", value, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultLessThanOrEqualTo(Boolean value) {
            addCriterion("CreditResult <=", value, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultIn(List<Boolean> values) {
            addCriterion("CreditResult in", values, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultNotIn(List<Boolean> values) {
            addCriterion("CreditResult not in", values, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultBetween(Boolean value1, Boolean value2) {
            addCriterion("CreditResult between", value1, value2, "creditResult");
            return (Criteria) this;
        }

        public Criteria andCreditResultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("CreditResult not between", value1, value2, "creditResult");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagIsNull() {
            addCriterion("AuditFlowFlag is null");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagIsNotNull() {
            addCriterion("AuditFlowFlag is not null");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagEqualTo(Boolean value) {
            addCriterion("AuditFlowFlag =", value, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagNotEqualTo(Boolean value) {
            addCriterion("AuditFlowFlag <>", value, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagGreaterThan(Boolean value) {
            addCriterion("AuditFlowFlag >", value, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("AuditFlowFlag >=", value, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagLessThan(Boolean value) {
            addCriterion("AuditFlowFlag <", value, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("AuditFlowFlag <=", value, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagIn(List<Boolean> values) {
            addCriterion("AuditFlowFlag in", values, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagNotIn(List<Boolean> values) {
            addCriterion("AuditFlowFlag not in", values, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("AuditFlowFlag between", value1, value2, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andAuditFlowFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("AuditFlowFlag not between", value1, value2, "auditFlowFlag");
            return (Criteria) this;
        }

        public Criteria andFinalResultIsNull() {
            addCriterion("FinalResult is null");
            return (Criteria) this;
        }

        public Criteria andFinalResultIsNotNull() {
            addCriterion("FinalResult is not null");
            return (Criteria) this;
        }

        public Criteria andFinalResultEqualTo(String value) {
            addCriterion("FinalResult =", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultNotEqualTo(String value) {
            addCriterion("FinalResult <>", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultGreaterThan(String value) {
            addCriterion("FinalResult >", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultGreaterThanOrEqualTo(String value) {
            addCriterion("FinalResult >=", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultLessThan(String value) {
            addCriterion("FinalResult <", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultLessThanOrEqualTo(String value) {
            addCriterion("FinalResult <=", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultLike(String value) {
            addCriterion("FinalResult like", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultNotLike(String value) {
            addCriterion("FinalResult not like", value, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultIn(List<String> values) {
            addCriterion("FinalResult in", values, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultNotIn(List<String> values) {
            addCriterion("FinalResult not in", values, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultBetween(String value1, String value2) {
            addCriterion("FinalResult between", value1, value2, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalResultNotBetween(String value1, String value2) {
            addCriterion("FinalResult not between", value1, value2, "finalResult");
            return (Criteria) this;
        }

        public Criteria andFinalRouteIsNull() {
            addCriterion("FinalRoute is null");
            return (Criteria) this;
        }

        public Criteria andFinalRouteIsNotNull() {
            addCriterion("FinalRoute is not null");
            return (Criteria) this;
        }

        public Criteria andFinalRouteEqualTo(String value) {
            addCriterion("FinalRoute =", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteNotEqualTo(String value) {
            addCriterion("FinalRoute <>", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteGreaterThan(String value) {
            addCriterion("FinalRoute >", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteGreaterThanOrEqualTo(String value) {
            addCriterion("FinalRoute >=", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteLessThan(String value) {
            addCriterion("FinalRoute <", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteLessThanOrEqualTo(String value) {
            addCriterion("FinalRoute <=", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteLike(String value) {
            addCriterion("FinalRoute like", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteNotLike(String value) {
            addCriterion("FinalRoute not like", value, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteIn(List<String> values) {
            addCriterion("FinalRoute in", values, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteNotIn(List<String> values) {
            addCriterion("FinalRoute not in", values, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteBetween(String value1, String value2) {
            addCriterion("FinalRoute between", value1, value2, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andFinalRouteNotBetween(String value1, String value2) {
            addCriterion("FinalRoute not between", value1, value2, "finalRoute");
            return (Criteria) this;
        }

        public Criteria andCreditLimitIsNull() {
            addCriterion("CreditLimit is null");
            return (Criteria) this;
        }

        public Criteria andCreditLimitIsNotNull() {
            addCriterion("CreditLimit is not null");
            return (Criteria) this;
        }

        public Criteria andCreditLimitEqualTo(BigDecimal value) {
            addCriterion("CreditLimit =", value, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitNotEqualTo(BigDecimal value) {
            addCriterion("CreditLimit <>", value, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitGreaterThan(BigDecimal value) {
            addCriterion("CreditLimit >", value, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CreditLimit >=", value, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitLessThan(BigDecimal value) {
            addCriterion("CreditLimit <", value, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CreditLimit <=", value, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitIn(List<BigDecimal> values) {
            addCriterion("CreditLimit in", values, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitNotIn(List<BigDecimal> values) {
            addCriterion("CreditLimit not in", values, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CreditLimit between", value1, value2, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andCreditLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CreditLimit not between", value1, value2, "creditLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitIsNull() {
            addCriterion("FinalLimit is null");
            return (Criteria) this;
        }

        public Criteria andFinalLimitIsNotNull() {
            addCriterion("FinalLimit is not null");
            return (Criteria) this;
        }

        public Criteria andFinalLimitEqualTo(BigDecimal value) {
            addCriterion("FinalLimit =", value, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitNotEqualTo(BigDecimal value) {
            addCriterion("FinalLimit <>", value, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitGreaterThan(BigDecimal value) {
            addCriterion("FinalLimit >", value, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FinalLimit >=", value, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitLessThan(BigDecimal value) {
            addCriterion("FinalLimit <", value, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FinalLimit <=", value, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitIn(List<BigDecimal> values) {
            addCriterion("FinalLimit in", values, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitNotIn(List<BigDecimal> values) {
            addCriterion("FinalLimit not in", values, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FinalLimit between", value1, value2, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andFinalLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FinalLimit not between", value1, value2, "finalLimit");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteIsNull() {
            addCriterion("ArtificialRoute is null");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteIsNotNull() {
            addCriterion("ArtificialRoute is not null");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteEqualTo(Byte value) {
            addCriterion("ArtificialRoute =", value, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteNotEqualTo(Byte value) {
            addCriterion("ArtificialRoute <>", value, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteGreaterThan(Byte value) {
            addCriterion("ArtificialRoute >", value, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteGreaterThanOrEqualTo(Byte value) {
            addCriterion("ArtificialRoute >=", value, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteLessThan(Byte value) {
            addCriterion("ArtificialRoute <", value, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteLessThanOrEqualTo(Byte value) {
            addCriterion("ArtificialRoute <=", value, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteIn(List<Byte> values) {
            addCriterion("ArtificialRoute in", values, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteNotIn(List<Byte> values) {
            addCriterion("ArtificialRoute not in", values, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteBetween(Byte value1, Byte value2) {
            addCriterion("ArtificialRoute between", value1, value2, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andArtificialRouteNotBetween(Byte value1, Byte value2) {
            addCriterion("ArtificialRoute not between", value1, value2, "artificialRoute");
            return (Criteria) this;
        }

        public Criteria andFobScoreIsNull() {
            addCriterion("FobScore is null");
            return (Criteria) this;
        }

        public Criteria andFobScoreIsNotNull() {
            addCriterion("FobScore is not null");
            return (Criteria) this;
        }

        public Criteria andFobScoreEqualTo(Integer value) {
            addCriterion("FobScore =", value, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreNotEqualTo(Integer value) {
            addCriterion("FobScore <>", value, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreGreaterThan(Integer value) {
            addCriterion("FobScore >", value, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("FobScore >=", value, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreLessThan(Integer value) {
            addCriterion("FobScore <", value, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreLessThanOrEqualTo(Integer value) {
            addCriterion("FobScore <=", value, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreIn(List<Integer> values) {
            addCriterion("FobScore in", values, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreNotIn(List<Integer> values) {
            addCriterion("FobScore not in", values, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreBetween(Integer value1, Integer value2) {
            addCriterion("FobScore between", value1, value2, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("FobScore not between", value1, value2, "fobScore");
            return (Criteria) this;
        }

        public Criteria andFobRankIsNull() {
            addCriterion("FobRank is null");
            return (Criteria) this;
        }

        public Criteria andFobRankIsNotNull() {
            addCriterion("FobRank is not null");
            return (Criteria) this;
        }

        public Criteria andFobRankEqualTo(Byte value) {
            addCriterion("FobRank =", value, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankNotEqualTo(Byte value) {
            addCriterion("FobRank <>", value, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankGreaterThan(Byte value) {
            addCriterion("FobRank >", value, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankGreaterThanOrEqualTo(Byte value) {
            addCriterion("FobRank >=", value, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankLessThan(Byte value) {
            addCriterion("FobRank <", value, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankLessThanOrEqualTo(Byte value) {
            addCriterion("FobRank <=", value, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankIn(List<Byte> values) {
            addCriterion("FobRank in", values, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankNotIn(List<Byte> values) {
            addCriterion("FobRank not in", values, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankBetween(Byte value1, Byte value2) {
            addCriterion("FobRank between", value1, value2, "fobRank");
            return (Criteria) this;
        }

        public Criteria andFobRankNotBetween(Byte value1, Byte value2) {
            addCriterion("FobRank not between", value1, value2, "fobRank");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreIsNull() {
            addCriterion("CashOutScore is null");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreIsNotNull() {
            addCriterion("CashOutScore is not null");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreEqualTo(Integer value) {
            addCriterion("CashOutScore =", value, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreNotEqualTo(Integer value) {
            addCriterion("CashOutScore <>", value, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreGreaterThan(Integer value) {
            addCriterion("CashOutScore >", value, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("CashOutScore >=", value, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreLessThan(Integer value) {
            addCriterion("CashOutScore <", value, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreLessThanOrEqualTo(Integer value) {
            addCriterion("CashOutScore <=", value, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreIn(List<Integer> values) {
            addCriterion("CashOutScore in", values, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreNotIn(List<Integer> values) {
            addCriterion("CashOutScore not in", values, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreBetween(Integer value1, Integer value2) {
            addCriterion("CashOutScore between", value1, value2, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andCashOutScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("CashOutScore not between", value1, value2, "cashOutScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreIsNull() {
            addCriterion("AapplyScore is null");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreIsNotNull() {
            addCriterion("AapplyScore is not null");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreEqualTo(Integer value) {
            addCriterion("AapplyScore =", value, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreNotEqualTo(Integer value) {
            addCriterion("AapplyScore <>", value, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreGreaterThan(Integer value) {
            addCriterion("AapplyScore >", value, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("AapplyScore >=", value, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreLessThan(Integer value) {
            addCriterion("AapplyScore <", value, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreLessThanOrEqualTo(Integer value) {
            addCriterion("AapplyScore <=", value, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreIn(List<Integer> values) {
            addCriterion("AapplyScore in", values, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreNotIn(List<Integer> values) {
            addCriterion("AapplyScore not in", values, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreBetween(Integer value1, Integer value2) {
            addCriterion("AapplyScore between", value1, value2, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andAapplyScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("AapplyScore not between", value1, value2, "aapplyScore");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CreateDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CreateDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CreateDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CreateDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CreateDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CreateDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CreateDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CreateDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CreateDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LastUpdateDate is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LastUpdateDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LastUpdateDate =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LastUpdateDate <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LastUpdateDate >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdateDate >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LastUpdateDate <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdateDate <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LastUpdateDate in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LastUpdateDate not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LastUpdateDate between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdateDate not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultIsNull() {
            addCriterion("MannualAuditResult is null");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultIsNotNull() {
            addCriterion("MannualAuditResult is not null");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultEqualTo(Byte value) {
            addCriterion("MannualAuditResult =", value, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultNotEqualTo(Byte value) {
            addCriterion("MannualAuditResult <>", value, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultGreaterThan(Byte value) {
            addCriterion("MannualAuditResult >", value, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultGreaterThanOrEqualTo(Byte value) {
            addCriterion("MannualAuditResult >=", value, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultLessThan(Byte value) {
            addCriterion("MannualAuditResult <", value, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultLessThanOrEqualTo(Byte value) {
            addCriterion("MannualAuditResult <=", value, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultIn(List<Byte> values) {
            addCriterion("MannualAuditResult in", values, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultNotIn(List<Byte> values) {
            addCriterion("MannualAuditResult not in", values, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultBetween(Byte value1, Byte value2) {
            addCriterion("MannualAuditResult between", value1, value2, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andMannualAuditResultNotBetween(Byte value1, Byte value2) {
            addCriterion("MannualAuditResult not between", value1, value2, "mannualAuditResult");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntIsNull() {
            addCriterion("HitGrayCnt is null");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntIsNotNull() {
            addCriterion("HitGrayCnt is not null");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntEqualTo(Integer value) {
            addCriterion("HitGrayCnt =", value, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntNotEqualTo(Integer value) {
            addCriterion("HitGrayCnt <>", value, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntGreaterThan(Integer value) {
            addCriterion("HitGrayCnt >", value, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("HitGrayCnt >=", value, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntLessThan(Integer value) {
            addCriterion("HitGrayCnt <", value, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntLessThanOrEqualTo(Integer value) {
            addCriterion("HitGrayCnt <=", value, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntIn(List<Integer> values) {
            addCriterion("HitGrayCnt in", values, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntNotIn(List<Integer> values) {
            addCriterion("HitGrayCnt not in", values, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntBetween(Integer value1, Integer value2) {
            addCriterion("HitGrayCnt between", value1, value2, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andHitGrayCntNotBetween(Integer value1, Integer value2) {
            addCriterion("HitGrayCnt not between", value1, value2, "hitGrayCnt");
            return (Criteria) this;
        }

        public Criteria andIsRefusedIsNull() {
            addCriterion("IsRefused is null");
            return (Criteria) this;
        }

        public Criteria andIsRefusedIsNotNull() {
            addCriterion("IsRefused is not null");
            return (Criteria) this;
        }

        public Criteria andIsRefusedEqualTo(Boolean value) {
            addCriterion("IsRefused =", value, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedNotEqualTo(Boolean value) {
            addCriterion("IsRefused <>", value, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedGreaterThan(Boolean value) {
            addCriterion("IsRefused >", value, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsRefused >=", value, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedLessThan(Boolean value) {
            addCriterion("IsRefused <", value, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedLessThanOrEqualTo(Boolean value) {
            addCriterion("IsRefused <=", value, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedIn(List<Boolean> values) {
            addCriterion("IsRefused in", values, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedNotIn(List<Boolean> values) {
            addCriterion("IsRefused not in", values, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedBetween(Boolean value1, Boolean value2) {
            addCriterion("IsRefused between", value1, value2, "isRefused");
            return (Criteria) this;
        }

        public Criteria andIsRefusedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsRefused not between", value1, value2, "isRefused");
            return (Criteria) this;
        }

        public Criteria andStepCodeIsNull() {
            addCriterion("StepCode is null");
            return (Criteria) this;
        }

        public Criteria andStepCodeIsNotNull() {
            addCriterion("StepCode is not null");
            return (Criteria) this;
        }

        public Criteria andStepCodeEqualTo(Byte value) {
            addCriterion("StepCode =", value, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeNotEqualTo(Byte value) {
            addCriterion("StepCode <>", value, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeGreaterThan(Byte value) {
            addCriterion("StepCode >", value, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeGreaterThanOrEqualTo(Byte value) {
            addCriterion("StepCode >=", value, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeLessThan(Byte value) {
            addCriterion("StepCode <", value, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeLessThanOrEqualTo(Byte value) {
            addCriterion("StepCode <=", value, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeIn(List<Byte> values) {
            addCriterion("StepCode in", values, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeNotIn(List<Byte> values) {
            addCriterion("StepCode not in", values, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeBetween(Byte value1, Byte value2) {
            addCriterion("StepCode between", value1, value2, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepCodeNotBetween(Byte value1, Byte value2) {
            addCriterion("StepCode not between", value1, value2, "stepCode");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("Step is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("Step is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(String value) {
            addCriterion("Step =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(String value) {
            addCriterion("Step <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(String value) {
            addCriterion("Step >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(String value) {
            addCriterion("Step >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(String value) {
            addCriterion("Step <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(String value) {
            addCriterion("Step <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLike(String value) {
            addCriterion("Step like", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotLike(String value) {
            addCriterion("Step not like", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<String> values) {
            addCriterion("Step in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<String> values) {
            addCriterion("Step not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(String value1, String value2) {
            addCriterion("Step between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(String value1, String value2) {
            addCriterion("Step not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentIsNull() {
            addCriterion("BSCreditComment is null");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentIsNotNull() {
            addCriterion("BSCreditComment is not null");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentEqualTo(String value) {
            addCriterion("BSCreditComment =", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentNotEqualTo(String value) {
            addCriterion("BSCreditComment <>", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentGreaterThan(String value) {
            addCriterion("BSCreditComment >", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentGreaterThanOrEqualTo(String value) {
            addCriterion("BSCreditComment >=", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentLessThan(String value) {
            addCriterion("BSCreditComment <", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentLessThanOrEqualTo(String value) {
            addCriterion("BSCreditComment <=", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentLike(String value) {
            addCriterion("BSCreditComment like", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentNotLike(String value) {
            addCriterion("BSCreditComment not like", value, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentIn(List<String> values) {
            addCriterion("BSCreditComment in", values, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentNotIn(List<String> values) {
            addCriterion("BSCreditComment not in", values, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentBetween(String value1, String value2) {
            addCriterion("BSCreditComment between", value1, value2, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBSCreditCommentNotBetween(String value1, String value2) {
            addCriterion("BSCreditComment not between", value1, value2, "BSCreditComment");
            return (Criteria) this;
        }

        public Criteria andBatchTimeIsNull() {
            addCriterion("BatchTime is null");
            return (Criteria) this;
        }

        public Criteria andBatchTimeIsNotNull() {
            addCriterion("BatchTime is not null");
            return (Criteria) this;
        }

        public Criteria andBatchTimeEqualTo(Date value) {
            addCriterion("BatchTime =", value, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeNotEqualTo(Date value) {
            addCriterion("BatchTime <>", value, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeGreaterThan(Date value) {
            addCriterion("BatchTime >", value, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("BatchTime >=", value, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeLessThan(Date value) {
            addCriterion("BatchTime <", value, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeLessThanOrEqualTo(Date value) {
            addCriterion("BatchTime <=", value, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeIn(List<Date> values) {
            addCriterion("BatchTime in", values, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeNotIn(List<Date> values) {
            addCriterion("BatchTime not in", values, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeBetween(Date value1, Date value2) {
            addCriterion("BatchTime between", value1, value2, "batchTime");
            return (Criteria) this;
        }

        public Criteria andBatchTimeNotBetween(Date value1, Date value2) {
            addCriterion("BatchTime not between", value1, value2, "batchTime");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeIsNull() {
            addCriterion("user_loaning_type is null");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeIsNotNull() {
            addCriterion("user_loaning_type is not null");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeEqualTo(Byte value) {
            addCriterion("user_loaning_type =", value, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeNotEqualTo(Byte value) {
            addCriterion("user_loaning_type <>", value, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeGreaterThan(Byte value) {
            addCriterion("user_loaning_type >", value, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_loaning_type >=", value, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeLessThan(Byte value) {
            addCriterion("user_loaning_type <", value, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeLessThanOrEqualTo(Byte value) {
            addCriterion("user_loaning_type <=", value, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeIn(List<Byte> values) {
            addCriterion("user_loaning_type in", values, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeNotIn(List<Byte> values) {
            addCriterion("user_loaning_type not in", values, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeBetween(Byte value1, Byte value2) {
            addCriterion("user_loaning_type between", value1, value2, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andUser_loaning_typeNotBetween(Byte value1, Byte value2) {
            addCriterion("user_loaning_type not between", value1, value2, "user_loaning_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeIsNull() {
            addCriterion("adjust_type is null");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeIsNotNull() {
            addCriterion("adjust_type is not null");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeEqualTo(Byte value) {
            addCriterion("adjust_type =", value, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeNotEqualTo(Byte value) {
            addCriterion("adjust_type <>", value, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeGreaterThan(Byte value) {
            addCriterion("adjust_type >", value, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeGreaterThanOrEqualTo(Byte value) {
            addCriterion("adjust_type >=", value, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeLessThan(Byte value) {
            addCriterion("adjust_type <", value, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeLessThanOrEqualTo(Byte value) {
            addCriterion("adjust_type <=", value, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeIn(List<Byte> values) {
            addCriterion("adjust_type in", values, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeNotIn(List<Byte> values) {
            addCriterion("adjust_type not in", values, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeBetween(Byte value1, Byte value2) {
            addCriterion("adjust_type between", value1, value2, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andAdjust_typeNotBetween(Byte value1, Byte value2) {
            addCriterion("adjust_type not between", value1, value2, "adjust_type");
            return (Criteria) this;
        }

        public Criteria andCredit_dateIsNull() {
            addCriterion("credit_date is null");
            return (Criteria) this;
        }

        public Criteria andCredit_dateIsNotNull() {
            addCriterion("credit_date is not null");
            return (Criteria) this;
        }

        public Criteria andCredit_dateEqualTo(Date value) {
            addCriterion("credit_date =", value, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateNotEqualTo(Date value) {
            addCriterion("credit_date <>", value, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateGreaterThan(Date value) {
            addCriterion("credit_date >", value, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("credit_date >=", value, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateLessThan(Date value) {
            addCriterion("credit_date <", value, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateLessThanOrEqualTo(Date value) {
            addCriterion("credit_date <=", value, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateIn(List<Date> values) {
            addCriterion("credit_date in", values, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateNotIn(List<Date> values) {
            addCriterion("credit_date not in", values, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateBetween(Date value1, Date value2) {
            addCriterion("credit_date between", value1, value2, "credit_date");
            return (Criteria) this;
        }

        public Criteria andCredit_dateNotBetween(Date value1, Date value2) {
            addCriterion("credit_date not between", value1, value2, "credit_date");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisIsNull() {
            addCriterion("RiskPricingRankBasis is null");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisIsNotNull() {
            addCriterion("RiskPricingRankBasis is not null");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisEqualTo(String value) {
            addCriterion("RiskPricingRankBasis =", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisNotEqualTo(String value) {
            addCriterion("RiskPricingRankBasis <>", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisGreaterThan(String value) {
            addCriterion("RiskPricingRankBasis >", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisGreaterThanOrEqualTo(String value) {
            addCriterion("RiskPricingRankBasis >=", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisLessThan(String value) {
            addCriterion("RiskPricingRankBasis <", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisLessThanOrEqualTo(String value) {
            addCriterion("RiskPricingRankBasis <=", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisLike(String value) {
            addCriterion("RiskPricingRankBasis like", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisNotLike(String value) {
            addCriterion("RiskPricingRankBasis not like", value, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisIn(List<String> values) {
            addCriterion("RiskPricingRankBasis in", values, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisNotIn(List<String> values) {
            addCriterion("RiskPricingRankBasis not in", values, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisBetween(String value1, String value2) {
            addCriterion("RiskPricingRankBasis between", value1, value2, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andRiskPricingRankBasisNotBetween(String value1, String value2) {
            addCriterion("RiskPricingRankBasis not between", value1, value2, "riskPricingRankBasis");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("OrderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("OrderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("OrderId =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("OrderId <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("OrderId >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("OrderId >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("OrderId <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("OrderId <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("OrderId in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("OrderId not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("OrderId between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("OrderId not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("ProductCode is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("ProductCode is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("ProductCode =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("ProductCode <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("ProductCode >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ProductCode >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("ProductCode <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("ProductCode <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("ProductCode like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("ProductCode not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("ProductCode in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("ProductCode not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("ProductCode between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("ProductCode not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andNodeInfoIsNull() {
            addCriterion("NodeInfo is null");
            return (Criteria) this;
        }

        public Criteria andNodeInfoIsNotNull() {
            addCriterion("NodeInfo is not null");
            return (Criteria) this;
        }

        public Criteria andNodeInfoEqualTo(String value) {
            addCriterion("NodeInfo =", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoNotEqualTo(String value) {
            addCriterion("NodeInfo <>", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoGreaterThan(String value) {
            addCriterion("NodeInfo >", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoGreaterThanOrEqualTo(String value) {
            addCriterion("NodeInfo >=", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoLessThan(String value) {
            addCriterion("NodeInfo <", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoLessThanOrEqualTo(String value) {
            addCriterion("NodeInfo <=", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoLike(String value) {
            addCriterion("NodeInfo like", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoNotLike(String value) {
            addCriterion("NodeInfo not like", value, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoIn(List<String> values) {
            addCriterion("NodeInfo in", values, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoNotIn(List<String> values) {
            addCriterion("NodeInfo not in", values, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoBetween(String value1, String value2) {
            addCriterion("NodeInfo between", value1, value2, "nodeInfo");
            return (Criteria) this;
        }

        public Criteria andNodeInfoNotBetween(String value1, String value2) {
            addCriterion("NodeInfo not between", value1, value2, "nodeInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 10 15:02:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_credit_risk
     *
     * @mbggenerated Fri Nov 10 15:02:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}